package com.iftikharhafeez.testapp.Models

data class Hobby(var title: String)

object Supplier{
    val Hobbies = listOf<Hobby>(
        Hobby("Swimming"),
        Hobby("Badminton"),
        Hobby("Reading"),
        Hobby("Soccer"),
        Hobby("Eating"),
        Hobby("Sleeping"),
        Hobby("Gaming"),
        Hobby("Walking"),
        Hobby("Programming"),
        Hobby("Smoking"),
        Hobby("Watching Moivies"),
        Hobby("Swimming"),
        Hobby("Badminton"),
        Hobby("Reading"),
        Hobby("Soccer"),
        Hobby("Eating"),
        Hobby("Sleeping"),
        Hobby("Gaming"),
        Hobby("Walking"),
        Hobby("Programming"),
        Hobby("Smoking"),
        Hobby("Watching Moivies"),
        Hobby("Swimming"),
        Hobby("Badminton"),
        Hobby("Reading"),
        Hobby("Soccer"),
        Hobby("Eating"),
        Hobby("Sleeping"),
        Hobby("Gaming"),
        Hobby("Walking"),
        Hobby("Programming"),
        Hobby("Smoking"),
        Hobby("Watching Moivies"),
        Hobby("Swimming"),
        Hobby("Badminton"),
        Hobby("Reading"),
        Hobby("Soccer"),
        Hobby("Eating"),
        Hobby("Sleeping"),
        Hobby("Gaming"),
        Hobby("Walking"),
        Hobby("Programming"),
        Hobby("Smoking"),
        Hobby("Watching Moivies"),
        Hobby("Swimming"),
        Hobby("Badminton"),
        Hobby("Reading"),
        Hobby("Soccer"),
        Hobby("Eating"),
        Hobby("Sleeping"),
        Hobby("Gaming"),
        Hobby("Walking"),
        Hobby("Programming"),
        Hobby("Smoking"),
        Hobby("Watching Moivies")

        )
}